import fs from 'fs';
import path from 'path';
import YAML from 'yaml';

const SOURCE_FILE = path.join(process.cwd(), 'references/tools/昨夜圆车.yaml');
const BASELINE_OUTPUT = path.join(process.cwd(), 'src/ARK_STATUSBAR/config/baseline.ts');
const SINGLE_CHAR_OUTPUT = path.join(process.cwd(), 'src/ARK_STATUSBAR/config/single_char_entries.ts');

try {
  console.log('Reading Worldbook YAML...');
  const fileContent = fs.readFileSync(SOURCE_FILE, 'utf8');
  
  console.log('Parsing YAML...');
  const data = YAML.parse(fileContent);
  
  if (!data || !data.条目 || !Array.isArray(data.条目)) {
    throw new Error('Invalid YAML structure: Missing "条目" array.');
  }

  const entries = data.条目;
  console.log(`Found ${entries.length} entries.`);

  const baselineState = {};
  const singleCharEntries = [];

  entries.forEach(entry => {
    if (entry.名称) {
      // 1. Build Baseline State
      const name = entry.名称;
      const enabled = entry.启用 === true;
      let type = 'selective'; // default to green light
      
      if (entry.激活策略 && entry.激活策略.类型) {
        if (entry.激活策略.类型 === '蓝灯') type = 'constant';
        else if (entry.激活策略.类型 === '绿灯') type = 'selective';
      }

      // Extract category from prefix, e.g., "[角色]阿米娅" -> "角色"
      let category = '未分类';
      const categoryMatch = name.match(/^\[(.*?)\]/);
      if (categoryMatch) {
        category = categoryMatch[1];
      }

      baselineState[name] = {
        enabled,
        type,
        category
      };

      // 2. Identify Single Character Entries
      let isSingleChar = false;
      if (entry.激活策略 && Array.isArray(entry.激活策略.关键字)) {
        for (const keyword of entry.激活策略.关键字) {
          if (typeof keyword === 'string' && keyword.length < 2) {
            isSingleChar = true;
            break;
          }
        }
      }

      if (isSingleChar) {
        singleCharEntries.push(name);
      }
    }
  });

  console.log(`Identified ${Object.keys(baselineState).length} baseline states.`);
  console.log(`Identified ${singleCharEntries.length} single-character entries.`);

  // Generate baseline.ts
  const baselineContent = `// Auto-generated by src/ARK_STATUSBAR/tools/generate_baseline.mjs
// Source: references/tools/昨夜圆车.yaml

export interface BaselineEntry {
  enabled: boolean;
  type: 'constant' | 'selective' | 'vectorized';
  category: string;
}

export const BASELINE_STATE: Record<string, BaselineEntry> = ${JSON.stringify(baselineState, null, 2)};
`;

  fs.writeFileSync(BASELINE_OUTPUT, baselineContent, 'utf8');
  console.log(`Generated: ${BASELINE_OUTPUT}`);

  // Generate single_char_entries.ts
  const singleCharContent = `// Auto-generated by references/tools/generate_baseline.mjs
// Source: references/tools/昨夜圆车.yaml

export const SINGLE_CHAR_ENTRIES: string[] = ${JSON.stringify(singleCharEntries, null, 2)};
`;

  fs.writeFileSync(SINGLE_CHAR_OUTPUT, singleCharContent, 'utf8');
  console.log(`Generated: ${SINGLE_CHAR_OUTPUT}`);

  console.log('Done.');

} catch (error) {
  console.error('Error generating baseline config:', error);
  process.exit(1);
}