// Auto-generated by src/ARK_STATUSBAR/tools/generate_baseline.mjs
// Source: references/tools/昨夜圆车.yaml

export interface BaselineEntry {
  enabled: boolean;
  type: 'constant' | 'selective' | 'vectorized';
  category: string;
}

export const BASELINE_STATE: Record<string, BaselineEntry> = {
  "备注": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "世界观": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "魔王（与特蕾西娅选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "状态栏（基本废弃，请保持关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "快回（抽象，非游玩请关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "历史（详细历史，非必须使用时请关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "历史大事件": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "干员档案（基本废弃，请保持关闭）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "干员档案-思考（同干员档案）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "前文明": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "泰拉": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "人类": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "黎博利": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "特别感谢版本彩蛋（豌豆写的，后由Fox进行文本优化）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "菲林": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "泰拉大陆调查团": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "凯尔希（本格，与Ama-10、巴别塔、预见末日的贤人选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡特斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "鲁珀": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "沃尔珀": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "佩洛": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莱伊": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "丰蹄": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "墨魉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡普里尼": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "乌萨斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "风笛": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "库兰塔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "埃拉菲亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "札拉克": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿纳缇": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "萨科塔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "龙": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "德拉克": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿斯兰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "斐迪亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "瓦伊凡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "萨卡兹": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "血魔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "温迪戈": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "石翼魔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "食腐者": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "女妖": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "变形者": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "巫妖": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "独眼巨人": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "笞心魔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "星熊（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "炎魔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "死魂灵": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "白金": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "海嗣": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿戈尔（人）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "依特拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "邪魔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "曼提柯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "麒麟": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿达克利斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "萨弗拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "瑞柏巴": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塞拉托": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "安努拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "罗德岛": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "拉特兰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡兹戴尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "炎": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "龙门": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "企鹅物流": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "乌萨斯帝国": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "整合运动": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "维多利亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "哥伦比亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "黑钢国际": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莱茵生命": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "叙拉古": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡西米尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿戈尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伊比利亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "萨尔贡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "汐斯塔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "谢拉格": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "喀兰贸易": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "萨米": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "深海教会": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莱塔尼亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "魏彦吾": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "特雷西斯（本格，与898年、内战选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "赫德雷": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "讯使": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梅菲斯特": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "霜星": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "碎骨": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "安玛、克雷松": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿丽娜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "巫王": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "W（本格，与维什戴尔选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "陈（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "诗怀雅（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塔露拉（斗士，与黑蛇选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿米娅（本格，与幼年、医疗、炉芯终曲选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "博士（男，以博士身份游玩时请关闭）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "鞭刃": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "忍冬": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "玛恩纳": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "临光（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "瑕光": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "苇草（本格，与幼龙、异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "Mon3tr锚定": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "死芒（本格，与幼龙选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "祐天寺若麦（本格，与菲林选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "左乐": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "华法琳": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "拉普兰德（本格，与幼狼、异格、无序的谦卑选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "德克萨斯（本格，与幼狼、异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "可颂": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "空": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "能天使（本格，与幼年、异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "林": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "银灰（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "望（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "初雪（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "崖心": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "锏": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "灵知": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "黑": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "煌（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "狮蝎": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "惊蛰（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "推进之王（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "斯卡蒂（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塑心（本格，与幼年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "归溟幽灵鲨（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "艾丽妮": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莫斯提马（本格，与少女选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "蕾缪安（本格，与少女选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "菲亚梅塔（本格，与少女选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "迷迭香": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "丰川祥子（本格，与萨卡兹选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "缪尔赛思": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "霍尔海雅": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伊芙利特": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塞雷娅": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "赫默（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "多萝西": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "白面鸮": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梅尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "星极": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "星源（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "三角初华（本格，与佩洛选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "若叶睦（本格，与卡特斯选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "八幡海铃（本格，与鲁珀选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "锡兰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "铃兰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "斥罪": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "红": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "羽毛笔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "暗索": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "麦哲伦": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "刻俄柏": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "特蕾西娅（本格，与898年、巴别塔、魔王选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伊内丝": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "科西切": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "文月": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "鼠王": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "角峰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "米莎": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "爱国者（本格，与博卓卡斯替选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "希尔德加德": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "浮士德": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "东国": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "白雪": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "普瑞赛斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "博士（女，以博士身份游玩时请关闭）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Mon3tr": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "可露希尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Mechanist": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "ACE": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Scout": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Sharp": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Pith": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Stormeye": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Touch": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Misery": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Raidian": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Outcast": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "年（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "夕（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "令（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "黍（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "余（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "重岳（本格，与朔选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "仇白": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "九": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Logos": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "U-Official": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "薇薇安娜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "歌蕾蒂娅": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "乌尔比安": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "浊心斯卡蒂（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "史尔特尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "耶拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿玛雅": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡谢娜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "水月": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "渡魂剑": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "澄闪": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "佩佩": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "菈玛莲（本格，与898年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "克丽斯腾": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "可萝尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿斯卡纶": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "源石与源石技艺": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "感染者与矿石病": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "祐天寺若麦（菲林，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "源石技术": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "深海猎人": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "兽主": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "闪灵": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "夜莺": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "三角初华（佩洛，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "格特鲁德": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "鸿雪": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "琴柳": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "绩（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "巨兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "丰川祥子（萨卡兹，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "巴别塔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "大帝": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "百炼嘉维尔（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "森蚺": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "特米米": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "妮芙": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "泥岩": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "提丰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "安洁莉娜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "号角": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "艾雅法拉（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "行箸": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "食铁兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "亚叶": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "寒檀": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "凛视": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "罗德岛论坛": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "桃金娘": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "子月": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阮薇薇": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "龙泡泡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "弑君者": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "早露": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "凛冬": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "烈夏": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "真理": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "古米": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "{{user}}锚定（以博士身份游玩时请关闭）": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "蔓德拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "和弦": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "若叶睦（卡特斯，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "罗德岛论坛（美化版，非游玩时请关闭）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "白铁": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "凯瑟琳": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "因陀罗": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "摩根": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "达格达": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "戴菲恩": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "杰西卡（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "雷蛇": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "芙兰卡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "涤火杰西卡（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "新约能天使（异格，与幼年、本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "睚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塔露拉（黑蛇，与斗士选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "八幡海铃（鲁珀，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "嘉维尔（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "幽灵鲨（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "缄默德克萨斯（异格，与少女、本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "荒芜拉普兰德（异格，与幼狼、本格、无序的谦卑选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "维什戴尔（异格，与本格W选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "司霆惊蛰（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "烛煌（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "歌利亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "恐鱼": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "海嗣种类": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "海嗣灭世（非游玩时请关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "你与她的终末（非游玩时请关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "塞壬唱片MSR": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "皇帝的利刃": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "麒麟R夜刀（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "夜刀（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "杜林": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "黑角（本格，与异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "巡林者": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "火龙S黑角（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "斩业星熊（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "遥": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "琳琅诗怀雅（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "假日威龙陈（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "罗德岛学院（非游玩时请关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "阿米娅（医疗，与幼年、本格、炉芯终曲选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "纯烬艾雅法拉（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "玫兰莎": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "宴": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "格拉尼": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "绮良": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "耀骑士临光（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "老鲤": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "缠丸": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "界园": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "器伥": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "焰影苇草（异格，与幼龙、本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "爱布拉娜·都柏林（幼龙，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "拉芙希妮·都柏林（幼龙，与本格、异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "司岁台": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "血魔大君": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Miss.Christine": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "食腐者之王（本格，与898年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "变形者集群": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "易（本格，与早年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "弗莱蒙特（本格，与898年选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "多利": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "大祭司": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "终末地（非游玩时请关闭）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "扎罗": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "锚定（有点用但不多）": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "罗素": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "乔万娜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伊斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "坎诺特": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "曼弗雷德": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "埃芒加德": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "隐德来希": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "空弦": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "维娜·维多利亚（异格，与本格推进之王选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "晓歌": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡莱莎": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "厄尔苏拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "苏苏洛": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "青枳": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "流明": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "寒芒克洛丝（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "克洛丝（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "极境": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "棘刺（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "引星棘刺（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "送葬人（本格，与幼年、异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "圣约送葬人（异格，与幼年、本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "安赛尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "预见末日的贤人（与Ama-10、凯尔希、巴别塔选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "杜宾": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "极光": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "傀影（本格，与酒神选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "酒神（异格，与本格傀影选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "“酒神”": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "蒂比": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "薄绿": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Mantra": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "圣愚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "管理员（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "陈千语（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "佩丽卡（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "伊冯（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "赛希（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "冬时": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "颉（整合了现有信息的先行版，非游玩时请关闭）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "折桠": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塞西莉亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伊蒂达": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "槐琥": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "槐天裴": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿米娅（幼年，与本格、医疗、炉芯终曲选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "阿米娅·炉芯终曲（与幼年、本格、医疗选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "暴行": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "吽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "孑": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "董阿伯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "阿消": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "天火": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "砾": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "深靛": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "蓝毒": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "芬（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "历阵锐枪芬（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "锡人": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Ama-10（与凯尔希、巴别塔、预见末日的贤人选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "凯尔希（巴别塔，与Ama-10、本格、预见末日的贤人选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "希尔达": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莫菲丝": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "特蕾西娅（898年，与本格、巴别塔、魔王选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "特蕾西娅（巴别塔，与本格、898年、魔王选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "特雷西斯（898年，与本格、内战选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "特雷西斯（内战，与本格、898年选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "蕾缪乐（幼年，与本格、异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "阿尔图罗·吉亚洛（幼年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "费德里科·吉亚洛（幼年，与本格、异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "蕾缪安（少女，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "莫斯提马（少女，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "奎萨图什塔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "萨卢斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "荒芜拉普兰德（无序的谦卑，与幼狼、本格、异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "朔（与本格重岳选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "望（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "令（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "黍（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "绩（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "易（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "年（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "夕（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "余（早年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "潘格尼尼": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梦城堡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "爱丽丝": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "贝娜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "海沫": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "娜仁图亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伺夜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "信仰搅拌机": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Ash": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Ela": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Lana": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Frost（彩六）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "弗莱蒙特（898年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "贝尔莎（非游玩魔王开局请关闭）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "大女妖（非游玩魔王开局时请关闭）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "菈玛莲（898年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "食腐者之王（898年，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "博卓卡斯替（与本格爱国者选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "Tachanka": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Fuze": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Doc": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Blitz": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "玛露西尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莱欧斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "森西": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "齐尔查克": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "罗小黑": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Lancet-2": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梓兰": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "老天师": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "泡普卡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "基建材料": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "工业材料": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "太傅": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "驼兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "杜林（族）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "际崖城": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梅兰德基金会": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "太尉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "菲亚梅塔（少女，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "切利尼娜·德克萨斯（幼狼，与本格、异格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "拉普兰德·萨卢佐（幼狼，与本格、异格、无序的谦卑选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "阿尔贝托": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "聆音": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "埃莉丝（肉鸽仙人跳之萨科塔修女）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "羽兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "瘤兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "沙地兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "裂兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "钳兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "云兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "循兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "鼷兽": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "锈锤": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "鲤氏侦探事务所": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "雷神工业": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "太阳谷机械工业": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "泰拉经济体系": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "泰拉货币体系": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "塔拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "高卢": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "“桥夹”克里夫": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "玻利瓦尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "米诺斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "雷姆必拓": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "约翰老妈": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "塔山生物科技": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "玫瑰报业联合集团": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梁洵": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "宁辞秋": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "柳儿": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "奎隆·摩诃萨埵权化（佛祖，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "奎隆（本格，与佛祖选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "战力分级标准": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "阿纳萨": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "雅拉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梅厄斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "逐魇骑士": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "血骑士": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "凛御银灰（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "圣聆初雪（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "溯光星源（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "焰尾": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "远牙": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "灰毫": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "野鬃": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "温蒂": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "嵯峨": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "帕拉斯": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡涅利安": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "蜜蜡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "异客": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "山": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "赫拉格": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "娜斯提": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "黑键": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "止颂": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "鬼": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "瑰盐": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "空构": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "桑葚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "安多恩": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "洁尔佩塔（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "艾尔黛拉（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "昼雪（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "骏卫（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "余烬（同终末地条目）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "（UI插件）返回键": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "（UI插件）开场美化": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "（上下文优化插件）EJS部分(注意设置扫描深度 = 0)": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "（插件通用）[InitVar]": {
    "enabled": true,
    "type": "constant",
    "category": "未分类"
  },
  "絮雨": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "九色鹿": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "构史成真了喵（非游玩时请关闭喵）": {
    "enabled": false,
    "type": "constant",
    "category": "未分类"
  },
  "红豆": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "深池": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "“校官”": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "“禁军小教头”": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "安纳斯塔西奥": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "峯驰物流": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "日落即逝": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "海蒂": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "调香师": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "火神": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "豆苗": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "淬羽赫默（异格，与本格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "香草": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "太古集团": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "拜松": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "欧厄尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "贾维": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "布洛卡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "奥斯塔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "“正义骑士号”": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "水灯心": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "芙蓉（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "濯尘芙蓉（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "白垩": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "炎熔（本格，与异格选一开）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "炎狱炎熔（异格，与本格选一开）": {
    "enabled": false,
    "type": "selective",
    "category": "未分类"
  },
  "米格鲁": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "珀茜瓦尔": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莉泽洛特": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "雷德": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "梅希亚": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "天空盒": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "澪": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "三船光平": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "斐尔迪南": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "小贾斯汀": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "杰斯顿": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "莫妮克": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "罗伊": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "炎客": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "芳汀": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "巫恋": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "卡夫卡": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "杏仁": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "四月": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "“灰礼帽”": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "灰喉": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "空爆": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "月见夜": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "斑点": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "贝林厄姆": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Aya": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Alty": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Dan": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "Frost（日落即逝）": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  },
  "伊万杰利斯塔十一世": {
    "enabled": true,
    "type": "selective",
    "category": "未分类"
  }
};
