// Auto-generated by references/tools/generate_baseline.mjs
// Source: references/tools/昨夜圆车.yaml

export const SINGLE_CHAR_ENTRIES: string[] = [
  "龙",
  "炎",
  "空",
  "林",
  "锏",
  "黑",
  "红",
  "九",
  "睚",
  "遥",
  "宴",
  "吽",
  "阿",
  "孑",
  "砾",
  "山",
  "鬼",
  "澪"
];
